### PR TITLE
Prep the repo for building a Node 20 binary

### PR DESCRIPTION
**Pull request by maschwenk**
1. Simplify the process outlined in the README
2. Upgrade node-gyp. Was unable to complete the installation until I did that. Can't find the logs 😢 
3. Update the Node version in the Dockerfile
4. Remove the `docker-compose` file. We're not composing multiple services/networks so I think overkill here. Easier to just build and then run in a one-liner IMO.

### CODE REVIEW

**Comment by luanxuechao** [comment]
Hi @pyramation, do you plan to merge this PR? My team have a security issue in node-gyp---->glob---->inflight, when the `node-gyp` upgrade to ^10, the inflight will removed.

**Comment by pyramation** [comment]
@benasher44 can you check this

**Comment by karlhorky** [comment]
I guess this can be closed, since the binaries for Node.js 20.x for linux/amd64, linux/arm64, darwin/arm64 have been published by @darora :

- https://github.com/launchql/libpg-query-node/issues/25#issuecomment-1882172638

**Comment by maschwenk** [comment]
I think the process of creating the binaries should be relatively reproducible by someone other than @darora? If only @darora can generate them it creates a bus factor going forward. AFAICT this repo as-is can't create the binaries because of issues in `node-gyp`.

**Comment by benasher44** [comment]
Any suggestions on a free place to host them? I think that's the main blocker right now. The build issues can be otherwise over come

**Comment by maschwenk** [comment]
@benasher44 that's a concern for sure, and no I don't have a great suggestion other than Github Releases? This PR doesn't try to tackle that, it's just to make it so that someone can checkout this repo and build at least the Linux binaries themselves.

**Comment by benasher44** [comment]
Fair! Change look good to me

**Pull request merged**
