### PR TITLE
Add bindings for pg_query_deparse_protobuf

### PR DESCRIPTION
**Pull request by tomquist**
This exposes deparse functionality to node.js. As of this issue the recommended approach is to generate a protobuf message from the JSON parse tree. One blocking issue is that `protobufjs` doesn't honor the `json_name` attribute so it isn't able to parse the existing structure into a protobuf message. There's [a PR](https://github.com/protobufjs/protobuf.js/pull/1825) to add this, however, this seems to be stale atm. In this PR I worked around this by directly pointing to the fork and generating a static JS model from it that I checked in. By checking in the model we could also point back to the original library, however, this makes updating the static model more cumbersome.

This pull request adds bindings for pg_query_deparse_protobuf to expose deparse functionality for Node.js. Currently, the [recommended approach](https://github.com/pganalyze/libpg_query/issues/178) is to generate a protobuf message from the JSON parse tree, but the protobufjs library doesn't honor the `json_name` attribute, which blocks parsing of the existing structure into a protobuf message. Although a PR to address this issue is available [here](https://github.com/protobufjs/protobuf.js/pull/1825), it seems stale at the moment.

In this PR, a workaround has been implemented by directly pointing to the fork and generating a static JS model from it that is checked in. While checking in the model allows for pointing back to the original library, it also makes updating the static model more cumbersome.

### CODE REVIEW

**Comment by jgoux** [comment]
This is awesome, thanks for your contribution! 🥳

**Comment by benasher44** [comment]
@tomquist would https://github.com/protocolbuffers/protobuf-javascript work instead?

**Comment by pyramation** [comment]
oops, I deleted `master` in an attempt to have more clarity, and it automatically closed this PR and I cannot seem to re-open it

@tomquist @benasher44 would love to see this re-open, at least for reference as a draft — sorry this!

**Comment by pyramation** [comment]
oops, I deleted `master` and a few others in an attempt to have more clarity around branches, keep similar naming convention as `libqg-query` and it automatically closed this PR — re-opening :)

**Comment by pyramation** [comment]
Would love to breathe life back into this! I've actually written protobuf parsers from scratch (see https://github.com/cosmology-tech/telescope)

@tomquist was this PR working for you? If so, I can look into the details of the option `json_name` and handle this

I could also make a nice pipeline for updating the proto.js that gets generated. I'll take a deeper look :)

**Comment by pyramation** [comment]
```
$ npm run test

> libpg-query@13.3.0 test
> mocha --timeout 5000



  Queries
    Sync Parsing
      ✓ should return a single-item parse result for common queries
      ✓ should support parsing multiple queries
      ✓ should not parse a bogus query
    Async parsing
      ✓ should return a promise resolving to same result
      ✓ should reject on bogus queries
    Deparsing
      ✓ async function should return a promise resolving to same SQL
      ✓ sync function should return a same SQL
      ✓ should reject on bogus input
    Fingerprint
      sync
        ✓ should not fingerprint a bogus query
        ✓ should fingerprint a query
      async
        ✓ should not fingerprint a bogus query
        ✓ should fingerprint a query

  PlPgSQL (async)
    ✓ should parse a function


  13 passing (12ms)
  ```
  
  NOTE: `yarn` doesn't work with Tom's branch, but `npm install` does :) 
  
  I think this is a great start, I can work with this!

**Comment by pyramation** [comment]
I'm gonna merge this PR into a dev branch, and work on this!

**Comment by pyramation** [comment]
new PR #63

**Pull request merged**
